### ISSUE TITLE
Difference between Tomcat and Wildfly Dockerfiles

### ISSUE THREAD

**Issue by ManoMarks** [dockersamples/javaee-demo#2]
In movieplex7/Dockerfile and movieplex7/Dockerfile.wildfly, the first stages appear identical. However, the last line of the first stage of Dockerfile is:
```
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTest
```
However, the last line of the first stage in Dockerfile.wildfly is:
```
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests
```

Is this intentionally different? Or should they be the same?

**Comment by spara** [comment]
correct syntax is -DskipTests, repo fixed and updated
