### ISSUE TITLE
Fix port issues on PWD

### ISSUE THREAD

**Issue by ManoMarks** [dockersamples/javaee-demo#9]
The main issue (which was actually two issues) is that the final K8s based deployment did not work properly. The root of the problem was two fold. First the Dockerfile has a port hard coded for the API_HOST URL in `add_ee_kube_pwd_host.sh`. This should have been hard coded to use the load balancer published port of 8080 but was instead mapped to the "Random" port assigned to the host. This is not a good practice as the Random port should change but the LB published port should be constant. Thus the Dockerfile needed to be updated and images rebuilt. This is in 
Second related issue is the port 8080 that the LB was publishing appears to conflict with something else deployed in the environments. We moved the LB external port to 8090 and moved the API_SERVER URL to 8090, rebuilt and redeployed and all was well.

**Comment by BretFisher** [comment]
Closing due to project archive
